version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iboss_frontend
    restart: always
    ports:
      - "3008:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=http://76.13.195.67:5001/api/
      - NODE_ENV=production
    networks:
      - iboss_network

networks:
  iboss_network:
    driver: bridge
